#!/bin/bash

echo Warning : old build system! Consider using CMake!
DIR=/usr/local/share/angort
mkdir -pv $DIR
cp libs/*.angso $DIR

mkdir -pv $DIR/cursesutils
cp curses/utils/*.ang $DIR/cursesutils
echo Warning : old build system! Consider using CMake!
