#!/bin/sh
# Builds all the standard set plus Jim's oddities and fun things
# like SDL bindings.

echo Warning : old build system! Consider using CMake!

./buildall

for d in mpc sdl midi serial vector2d udp curl curses diamond png osc
do
    echo $d
    cd $d
    ./build
    cd ..
done

echo Warning : old build system! Consider using CMake!
