#!/bin/bash
source ../base.sh
makewords id3

g++ -fPIC -g -c -Wall `pkg-config taglib --cflags` id3.plugin.cpp 

g++ -shared -Wl,-soname,id3.angso \
    -o ../libs/id3.angso \
    id3.plugin.o\
    `pkg-config taglib --libs`\

