#!/bin/bash
source ../base.sh

makewords time


g++ -fPIC -O3 -c -Wall time.plugin.cpp

g++  -shared \
    time.plugin.o \
    -Wl,-soname,time.angso \
    -o ../libs/time.angso \
    -Wl,--whole-archive -lrt -Wl,--no-whole-archive
 
    

